-- MySQL Script generated by MySQL Workbench
-- Mon Sep 30 13:07:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `book_store` ;

-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book_store` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `book_store` ;

-- -----------------------------------------------------
-- Table `book_store`.`book_catalouge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`book_catalouge` ;

CREATE TABLE IF NOT EXISTS `book_store`.`book_catalouge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NULL DEFAULT NULL,
  `catalouge_id` INT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `BOOK_KEY` (`book_id` ASC) INVISIBLE,
  INDEX `CATALOUGE_KEY` (`catalouge_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8
COLLATE = armscii8_bin;


-- -----------------------------------------------------
-- Table `book_store`.`cart_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`cart_detail` ;

CREATE TABLE IF NOT EXISTS `book_store`.`cart_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NULL DEFAULT NULL,
  `book_id` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `BOOK_KEY` (`book_id` ASC) INVISIBLE,
  INDEX `CART_KEY` (`cart_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`book_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`book_review` ;

CREATE TABLE IF NOT EXISTS `book_store`.`book_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `review` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `BOOK_KEY` (`book_id` ASC) INVISIBLE,
  INDEX `USER_KEY` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`book` ;

CREATE TABLE IF NOT EXISTS `book_store`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) CHARACTER SET 'armscii8' COLLATE 'armscii8_bin' NOT NULL,
  `author` VARCHAR(255) CHARACTER SET 'armscii8' COLLATE 'armscii8_bin' NOT NULL,
  `publisher` VARCHAR(50) CHARACTER SET 'armscii8' COLLATE 'armscii8_bin' NOT NULL,
  `avaliable` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `created_on` DATE NULL,
  `is_active` ENUM('Y', 'N') CHARACTER SET 'armscii8' COLLATE 'armscii8_bin' NULL DEFAULT 'N',
  `genre_id` INT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `KEY` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `FK_book_book_catalouge`
    FOREIGN KEY (`id`)
    REFERENCES `book_store`.`book_catalouge` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_book_cart_detail`
    FOREIGN KEY (`id`)
    REFERENCES `book_store`.`cart_detail` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_book_book_review`
    FOREIGN KEY (`id`)
    REFERENCES `book_store`.`book_review` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8
COLLATE = armscii8_bin;


-- -----------------------------------------------------
-- Table `book_store`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`cart` ;

CREATE TABLE IF NOT EXISTS `book_store`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `address` INT NULL DEFAULT NULL,
  `phone` INT NULL DEFAULT NULL,
  `payment_id` INT NULL DEFAULT NULL,
  `create_date` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `KEY` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_cart_cart_detail`
    FOREIGN KEY (`id`)
    REFERENCES `book_store`.`cart_detail` (`cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`catalouge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`catalouge` ;

CREATE TABLE IF NOT EXISTS `book_store`.`catalouge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(50) CHARACTER SET 'armscii8' COLLATE 'armscii8_bin' NOT NULL,
  `is_active` ENUM('Y', 'N') CHARACTER SET 'armscii8' COLLATE 'armscii8_bin' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'armscii8' COLLATE 'armscii8_bin' NOT NULL,
  PRIMARY KEY USING BTREE (`id`),
  CONSTRAINT `FK_catalouge`
    FOREIGN KEY (`id`)
    REFERENCES `book_store`.`book_catalouge` (`catalouge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8
COLLATE = armscii8_bin;


-- -----------------------------------------------------
-- Table `book_store`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`genre` ;

CREATE TABLE IF NOT EXISTS `book_store`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` INT NULL DEFAULT NULL,
  `description` INT NULL DEFAULT NULL,
  `is_active` ENUM('Y', 'N') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_genre_book`
    FOREIGN KEY (`id`)
    REFERENCES `book_store`.`book` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `book_store`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`user` ;

CREATE TABLE IF NOT EXISTS `book_store`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_user_book_review`
    FOREIGN KEY (`id`)
    REFERENCES `book_store`.`book_review` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_user_cart`
    FOREIGN KEY (`id`)
    REFERENCES `book_store`.`cart` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
